// app/study-visa/top-universities/page.tsx

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Top Universities for International Students | Skyland Immigration",
  description:
    "Explore the world's best universities for study abroad programs. Latest QS World University Rankings 2025. Comprehensive list of top 500 universities worldwide. Trusted by international students. Apply with Skyland Immigration.",
};

const universities = [
  { name: "Massachusetts Institute of Technology (MIT)", country: "USA", field: "Engineering, Computer Science", rank: 1 },
  { name: "Imperial College London", country: "UK", field: "Engineering, Medicine, Science", rank: 2 },
  { name: "University of Oxford", country: "UK", field: "Arts, Sciences, Medicine", rank: 3 },
  { name: "Harvard University", country: "USA", field: "Law, Medicine, Business", rank: 4 },
  { name: "University of Cambridge", country: "UK", field: "Sciences, Engineering, Arts", rank: 5 },
  { name: "ETH Zurich", country: "Switzerland", field: "Engineering, Technology", rank: 6 },
  { name: "National University of Singapore", country: "Singapore", field: "Engineering, Technology", rank: 7 },
  { name: "University College London (UCL)", country: "UK", field: "Arts, Sciences, Engineering", rank: 8 },
  { name: "Stanford University", country: "USA", field: "Technology, Business", rank: 9 },
  { name: "University of California, Berkeley", country: "USA", field: "Sciences, Engineering", rank: 10 },
  { name: "University of Chicago", country: "USA", field: "Economics, Business", rank: 11 },
  { name: "Nanyang Technological University", country: "Singapore", field: "Engineering, Business", rank: 12 },
  { name: "Peking University", country: "China", field: "Sciences, Arts", rank: 13 },
  { name: "University of Pennsylvania", country: "USA", field: "Business, Medicine", rank: 14 },
  { name: "Tsinghua University", country: "China", field: "Engineering, Sciences", rank: 15 },
  { name: "University of Edinburgh", country: "UK", field: "Arts, Sciences", rank: 16 },
  { name: "EPFL", country: "Switzerland", field: "Engineering, Technology", rank: 17 },
  { name: "Yale University", country: "USA", field: "Law, Arts", rank: 18 },
  { name: "University of Hong Kong (HKU)", country: "Hong Kong", field: "Medicine, Business", rank: 19 },
  { name: "University of Tokyo", country: "Japan", field: "Sciences, Engineering", rank: 20 },
  { name: "Johns Hopkins University", country: "USA", field: "Medicine, Sciences", rank: 21 },
  { name: "University of Toronto", country: "Canada", field: "Medicine, Arts", rank: 22 },
  { name: "Cornell University", country: "USA", field: "Engineering, Agriculture", rank: 23 },
  { name: "University of Michigan", country: "USA", field: "Engineering, Arts", rank: 24 },
  { name: "Australian National University", country: "Australia", field: "Research, Sciences", rank: 25 },
  { name: "Princeton University", country: "USA", field: "Sciences, Engineering", rank: 26 },
  { name: "University of Manchester", country: "UK", field: "Engineering, Sciences", rank: 27 },
  { name: "Technical University of Munich", country: "Germany", field: "Engineering, Technology", rank: 28 },
  { name: "University of California, Los Angeles", country: "USA", field: "Arts, Sciences", rank: 29 },
  { name: "McGill University", country: "Canada", field: "Medicine, Engineering", rank: 30 },
  
  { name: "Northwestern University", country: "USA", field: "Journalism, Medicine", rank: 31 },
  { name: "University of Melbourne", country: "Australia", field: "Arts, Sciences", rank: 32 },
  { name: "Kyoto University", country: "Japan", field: "Sciences, Engineering", rank: 33 },
  { name: "Seoul National University", country: "South Korea", field: "Engineering, Sciences", rank: 34 },
  { name: "University of British Columbia", country: "Canada", field: "Environment, Technology", rank: 35 },
  { name: "King's College London", country: "UK", field: "Medicine, Humanities", rank: 36 },
  { name: "Chinese University of Hong Kong", country: "Hong Kong", field: "Business, Sciences", rank: 37 },
  { name: "University of Sydney", country: "Australia", field: "Research, Medicine", rank: 38 },
  { name: "University of California, San Diego", country: "USA", field: "Biology, Engineering", rank: 39 },
  { name: "Paris Sciences et Lettres", country: "France", field: "Arts, Sciences", rank: 40 },
  { name: "KAIST", country: "South Korea", field: "Technology, Engineering", rank: 41 },
  { name: "New York University", country: "USA", field: "Arts, Business", rank: 42 },
  { name: "University of New South Wales", country: "Australia", field: "Engineering, Business", rank: 43 },
  { name: "Zhejiang University", country: "China", field: "Technology, Sciences", rank: 44 },
  { name: "University of Queensland", country: "Australia", field: "Life Sciences, Engineering", rank: 45 },
  { name: "Delft University of Technology", country: "Netherlands", field: "Engineering, Design", rank: 46 },
  { name: "University of Wisconsin-Madison", country: "USA", field: "Research, Agriculture", rank: 47 },
  { name: "University of Illinois", country: "USA", field: "Engineering, Sciences", rank: 48 },
  { name: "University of Amsterdam", country: "Netherlands", field: "Social Sciences, Research", rank: 49 },
  { name: "Tokyo Institute of Technology", country: "Japan", field: "Technology, Science", rank: 50 },
  { name: "Monash University", country: "Australia", field: "Engineering, Medicine", rank: 51 },
  { name: "Shanghai Jiao Tong University", country: "China", field: "Engineering, Medicine", rank: 52 },
  { name: "Technical University of Berlin", country: "Germany", field: "Engineering, Technology", rank: 53 },
  { name: "University of Texas at Austin", country: "USA", field: "Technology, Business", rank: 54 },
  { name: "Carnegie Mellon University", country: "USA", field: "Computer Science, Arts", rank: 55 },
  { name: "University of Warwick", country: "UK", field: "Mathematics, Business", rank: 56 },
  { name: "University of Glasgow", country: "UK", field: "Medicine, Arts", rank: 57 },
  { name: "Ludwig Maximilian University Munich", country: "Germany", field: "Research, Medicine", rank: 58 },
  { name: "University of Copenhagen", country: "Denmark", field: "Sciences, Health", rank: 59 },
  { name: "University of Bristol", country: "UK", field: "Engineering, Arts", rank: 60 },

  { name: "Hong Kong University of Science and Technology", country: "Hong Kong", field: "Technology, Business", rank: 61 },
  { name: "Osaka University", country: "Japan", field: "Sciences, Engineering", rank: 62 },
  { name: "University of Washington", country: "USA", field: "Medicine, Engineering", rank: 63 },
  { name: "University of Edinburgh", country: "UK", field: "Arts, Sciences", rank: 64 },
  { name: "Sorbonne University", country: "France", field: "Sciences, Humanities", rank: 65 },
  { name: "University of Auckland", country: "New Zealand", field: "Engineering, Arts", rank: 66 },
  { name: "Georgia Institute of Technology", country: "USA", field: "Engineering, Computing", rank: 67 },
  { name: "KU Leuven", country: "Belgium", field: "Engineering, Medicine", rank: 68 },
  { name: "University of Birmingham", country: "UK", field: "Sports, Engineering", rank: 69 },
  { name: "University of Zurich", country: "Switzerland", field: "Medicine, Economics", rank: 70 },
  { name: "University of Sheffield", country: "UK", field: "Engineering, Sciences", rank: 71 },
  { name: "University of Southampton", country: "UK", field: "Engineering, Ocean Science", rank: 72 },
  { name: "University of Leeds", country: "UK", field: "Business, Engineering", rank: 73 },
  { name: "Tohoku University", country: "Japan", field: "Physics, Engineering", rank: 74 },
  { name: "University of Western Australia", country: "Australia", field: "Agriculture, Marine Science", rank: 75 },
  { name: "Durham University", country: "UK", field: "Arts, Sciences", rank: 76 },
  { name: "University of Alberta", country: "Canada", field: "Engineering, Sciences", rank: 77 },
  { name: "University of Science and Technology of China", country: "China", field: "Sciences, Engineering", rank: 78 },
  { name: "Trinity College Dublin", country: "Ireland", field: "Arts, Sciences", rank: 79 },
  { name: "University of Nottingham", country: "UK", field: "Medicine, Engineering", rank: 80 },
  { name: "Rice University", country: "USA", field: "Engineering, Natural Sciences", rank: 81 },
  { name: "University of Oslo", country: "Norway", field: "Medicine, Social Sciences", rank: 82 },
  { name: "University of Montreal", country: "Canada", field: "Medicine, Arts", rank: 83 },
  { name: "University of California, Davis", country: "USA", field: "Agriculture, Veterinary", rank: 84 },
  { name: "Utrecht University", country: "Netherlands", field: "Life Sciences, Humanities", rank: 85 },
  { name: "University of Geneva", country: "Switzerland", field: "International Relations, Sciences", rank: 86 },
  { name: "Boston University", country: "USA", field: "Medicine, Communications", rank: 87 },
  { name: "University of North Carolina", country: "USA", field: "Medicine, Social Sciences", rank: 88 },
  { name: "University of Helsinki", country: "Finland", field: "Arts, Sciences", rank: 89 },
  { name: "University of Vienna", country: "Austria", field: "Social Sciences, Humanities", rank: 90 },
  { name: "University of California, Santa Barbara", country: "USA", field: "Physics, Engineering", rank: 91 },
  { name: "University of Adelaide", country: "Australia", field: "Wine Science, Engineering", rank: 92 },
  { name: "University of Pittsburgh", country: "USA", field: "Medicine, Engineering", rank: 93 },
  { name: "Stockholm University", country: "Sweden", field: "Sciences, Humanities", rank: 94 },
  { name: "Queen Mary University of London", country: "UK", field: "Medicine, Engineering", rank: 95 },
  { name: "Lancaster University", country: "UK", field: "Management, Sciences", rank: 96 },
  { name: "Technical University of Denmark", country: "Denmark", field: "Engineering, Life Sciences", rank: 97 },
  { name: "University of Bern", country: "Switzerland", field: "Medicine, Sciences", rank: 98 },
  { name: "University of Basel", country: "Switzerland", field: "Life Sciences, Arts", rank: 99 },
  { name: "University of Sussex", country: "UK", field: "Development Studies, Sciences", rank: 100 },
  
  // Rankings 101-150
  { name: "University of Florida", country: "USA", field: "Agriculture, Engineering", rank: 101 },
  { name: "University of Groningen", country: "Netherlands", field: "Life Sciences, Business", rank: 102 },
  { name: "University of Maryland", country: "USA", field: "Engineering, Computer Science", rank: 103 },
  { name: "University of Technology Sydney", country: "Australia", field: "Technology, Design", rank: 104 },
  { name: "University of Lausanne", country: "Switzerland", field: "Business, Life Sciences", rank: 105 },
  { name: "Cardiff University", country: "UK", field: "Medicine, Engineering", rank: 106 },
  { name: "University of Bergen", country: "Norway", field: "Marine Science, Medicine", rank: 107 },
  { name: "Technical University of Madrid", country: "Spain", field: "Engineering, Architecture", rank: 108 },
  { name: "University of Exeter", country: "UK", field: "Environmental Science, Business", rank: 109 },
  { name: "University of Gothenburg", country: "Sweden", field: "Medicine, Arts", rank: 110 },
  { name: "University of Liverpool", country: "UK", field: "Engineering, Medicine", rank: 111 },
  { name: "University of Ottawa", country: "Canada", field: "Law, Medicine", rank: 112 },
  { name: "Aarhus University", country: "Denmark", field: "Business, Sciences", rank: 113 },
  { name: "University of California, Irvine", country: "USA", field: "Computer Science, Biology", rank: 114 },
  { name: "Vrije Universiteit Amsterdam", country: "Netherlands", field: "Psychology, Business", rank: 115 },
  { name: "University of Reading", country: "UK", field: "Agriculture, Business", rank: 116 },
  { name: "University of Waterloo", country: "Canada", field: "Engineering, Mathematics", rank: 117 },
  { name: "Newcastle University", country: "UK", field: "Medicine, Engineering", rank: 118 },
  { name: "Queensland University of Technology", country: "Australia", field: "Technology, Creative Arts", rank: 119 },
  { name: "University of Aberdeen", country: "UK", field: "Medicine, Engineering", rank: 120 },
  { name: "University of Twente", country: "Netherlands", field: "Technology, Social Sciences", rank: 121 },
  { name: "University of East Anglia", country: "UK", field: "Environmental Sciences, Literature", rank: 122 },
  { name: "University of Antwerp", country: "Belgium", field: "Medicine, Sciences", rank: 123 },
  { name: "University of Bath", country: "UK", field: "Engineering, Management", rank: 124 },
  { name: "Macquarie University", country: "Australia", field: "Business, Sciences", rank: 125 },
  { name: "University of Leicester", country: "UK", field: "Space Research, Medicine", rank: 126 },
  { name: "Radboud University", country: "Netherlands", field: "Medicine, Sciences", rank: 127 },
  { name: "University of Wollongong", country: "Australia", field: "Engineering, IT", rank: 128 },
  { name: "University of Surrey", country: "UK", field: "Hospitality, Engineering", rank: 129 },
  { name: "University of Mannheim", country: "Germany", field: "Business, Social Sciences", rank: 130 },
  { name: "Université de Montréal", country: "Canada", field: "Medicine, Arts", rank: 131 },
  { name: "University of Tasmania", country: "Australia", field: "Marine Science, Agriculture", rank: 132 },
  { name: "Vienna University of Technology", country: "Austria", field: "Engineering, Architecture", rank: 133 },
  { name: "University of Strathclyde", country: "UK", field: "Engineering, Business", rank: 134 },
  { name: "University of Graz", country: "Austria", field: "Law, Humanities", rank: 135 },
  { name: "Curtin University", country: "Australia", field: "Mining, Engineering", rank: 136 },
  { name: "University of Kent", country: "UK", field: "Arts, Sciences", rank: 137 },
  { name: "University of Porto", country: "Portugal", field: "Engineering, Medicine", rank: 138 },
  { name: "University of Warsaw", country: "Poland", field: "Physics, Mathematics", rank: 139 },
  { name: "University of Bologna", country: "Italy", field: "Arts, Engineering", rank: 140 },
  { name: "University of Victoria", country: "Canada", field: "Ocean Sciences, Engineering", rank: 141 },
  { name: "University of Bergen", country: "Norway", field: "Marine Science, Climate Research", rank: 142 },
  { name: "University of Waikato", country: "New Zealand", field: "Management, Computing", rank: 143 },
  { name: "University of Stirling", country: "UK", field: "Sports, Media", rank: 144 },
  { name: "University of Otago", country: "New Zealand", field: "Health Sciences, Sciences", rank: 145 },
  { name: "Maastricht University", country: "Netherlands", field: "Business, Health", rank: 146 },
  { name: "University of Dundee", country: "UK", field: "Life Sciences, Art", rank: 147 },
  { name: "University of Lisbon", country: "Portugal", field: "Engineering, Sciences", rank: 148 },
  { name: "University of Milan", country: "Italy", field: "Medicine, Humanities", rank: 149 },
  { name: "University of Canterbury", country: "New Zealand", field: "Engineering, Forestry", rank: 150 },

  // Rankings 151-200
  { name: "Lund University", country: "Sweden", field: "Engineering, Medicine", rank: 151 },
  { name: "University of Bremen", country: "Germany", field: "Marine Science, Space Technology", rank: 152 },
  { name: "University of Padua", country: "Italy", field: "Medicine, Engineering", rank: 153 },
  { name: "University of Ghent", country: "Belgium", field: "Biotechnology, Engineering", rank: 154 },
  { name: "University of Bordeaux", country: "France", field: "Wine Science, Medicine", rank: 155 },
  { name: "University of Innsbruck", country: "Austria", field: "Mountain Research, Physics", rank: 156 },
  { name: "University of Turku", country: "Finland", field: "Medicine, Education", rank: 157 },
  { name: "University of Cologne", country: "Germany", field: "Economics, Medicine", rank: 158 },
  { name: "University of Navarra", country: "Spain", field: "Business, Medicine", rank: 159 },
  { name: "University of Trento", country: "Italy", field: "International Studies, Science", rank: 160 },
  { name: "University of Konstanz", country: "Germany", field: "Chemistry, Politics", rank: 161 },
  { name: "University of Tampere", country: "Finland", field: "Social Sciences, Technology", rank: 162 },
  { name: "University of Trieste", country: "Italy", field: "Physics, Engineering", rank: 163 },
  { name: "University of Coimbra", country: "Portugal", field: "Medicine, Engineering", rank: 164 },
  { name: "University of Pisa", country: "Italy", field: "Computer Science, Engineering", rank: 165 },
  { name: "University of Salamanca", country: "Spain", field: "Languages, Sciences", rank: 166 },
  { name: "University of Jyväskylä", country: "Finland", field: "Sport Sciences, Education", rank: 167 },
  { name: "University of Valencia", country: "Spain", field: "Chemistry, Medicine", rank: 168 },
  { name: "University of Siena", country: "Italy", field: "Medicine, Economics", rank: 169 },
  { name: "University of Zaragoza", country: "Spain", field: "Engineering, Veterinary", rank: 170 },
  { name: "University of Oulu", country: "Finland", field: "Wireless Technology, Mining", rank: 171 },
  { name: "University of Pavia", country: "Italy", field: "Medicine, Music", rank: 172 },
  { name: "University of Vigo", country: "Spain", field: "Marine Sciences, Engineering", rank: 173 },
  { name: "University of Parma", country: "Italy", field: "Food Science, Engineering", rank: 174 },
  { name: "University of Murcia", country: "Spain", field: "Biology, Arts", rank: 175 },
  { name: "University of Eastern Finland", country: "Finland", field: "Forestry, Health Sciences", rank: 176 },
  { name: "University of Modena", country: "Italy", field: "Automotive, Medicine", rank: 177 },
  { name: "University of A Coruña", country: "Spain", field: "Marine Science, Engineering", rank: 178 },
  { name: "University of Ferrara", country: "Italy", field: "Architecture, Medicine", rank: 179 },
  { name: "University of Oviedo", country: "Spain", field: "Mining, Chemistry", rank: 180 },
  { name: "University of Verona", country: "Italy", field: "Economics, Medicine", rank: 181 },
  { name: "University of Málaga", country: "Spain", field: "Technology, Tourism", rank: 182 },
  { name: "University of Palermo", country: "Italy", field: "Architecture, Engineering", rank: 183 },
  { name: "University of Valladolid", country: "Spain", field: "Engineering, Arts", rank: 184 },
  { name: "University of Catania", country: "Italy", field: "Physics, Agriculture", rank: 185 },
  { name: "University of Alcalá", country: "Spain", field: "Medicine, Humanities", rank: 186 },
  { name: "University of Genoa", country: "Italy", field: "Marine Science, Engineering", rank: 187 },
  { name: "University of Santiago de Compostela", country: "Spain", field: "Chemistry, Medicine", rank: 188 },
  { name: "University of Perugia", country: "Italy", field: "Agriculture, Medicine", rank: 189 },
  { name: "University of the Basque Country", country: "Spain", field: "Engineering, Arts", rank: 190 },
  { name: "University of Calabria", country: "Italy", field: "Engineering, Economics", rank: 191 },
  { name: "University of Castilla-La Mancha", country: "Spain", field: "Engineering, Environment", rank: 192 },
  { name: "University of Salerno", country: "Italy", field: "Computer Science, Chemistry", rank: 193 },
  { name: "University of Las Palmas", country: "Spain", field: "Marine Science, Tourism", rank: 194 },
  { name: "University of Messina", country: "Italy", field: "Medicine, Marine Science", rank: 195 },
  { name: "University of Cantabria", country: "Spain", field: "Engineering, Medicine", rank: 196 },
  { name: "University of L'Aquila", country: "Italy", field: "Physics, Engineering", rank: 197 },
  { name: "University of Extremadura", country: "Spain", field: "Veterinary, Engineering", rank: 198 },
  { name: "University of Cagliari", country: "Italy", field: "Engineering, Medicine", rank: 199 },
  { name: "University of Jaén", country: "Spain", field: "Olive Oil Research, Engineering", rank: 200 },

  // Rankings 201-250
  { name: "University of Aix-Marseille", country: "France", field: "Marine Science, Medicine", rank: 201 },
  { name: "University of Göttingen", country: "Germany", field: "Physics, Agriculture", rank: 202 },
  { name: "University of Lille", country: "France", field: "Health Sciences, Technology", rank: 203 },
  { name: "University of Münster", country: "Germany", field: "Religion, Medicine", rank: 204 },
  { name: "University of Nice Sophia Antipolis", country: "France", field: "Mathematics, Marine Science", rank: 205 },
  { name: "University of Würzburg", country: "Germany", field: "Medicine, Physics", rank: 206 },
  { name: "University of Strasbourg", country: "France", field: "Chemistry, Life Sciences", rank: 207 },
  { name: "University of Erlangen-Nuremberg", country: "Germany", field: "Engineering, Medicine", rank: 208 },
  { name: "University of Toulouse", country: "France", field: "Aerospace, Economics", rank: 209 },
  { name: "University of Heidelberg", country: "Germany", field: "Medicine, Physics", rank: 210 },
  { name: "University of Montpellier", country: "France", field: "Agriculture, Medicine", rank: 211 },
  { name: "University of Kiel", country: "Germany", field: "Marine Science, Medicine", rank: 212 },
  { name: "University of Nantes", country: "France", field: "Digital Sciences, Medicine", rank: 213 },
  { name: "University of Regensburg", country: "Germany", field: "Medicine, Business", rank: 214 },
  { name: "University of Rennes", country: "France", field: "Digital Technology, Health", rank: 215 },
  { name: "University of Ulm", country: "Germany", field: "Medicine, Mathematics", rank: 216 },
  { name: "University of Grenoble Alpes", country: "France", field: "Physics, Computer Science", rank: 217 },
  { name: "University of Jena", country: "Germany", field: "Optics, Life Sciences", rank: 218 },
  { name: "University of Lorraine", country: "France", field: "Engineering, Materials Science", rank: 219 },
  { name: "University of Rostock", country: "Germany", field: "Medicine, Marine Science", rank: 220 },
  { name: "University of Poitiers", country: "France", field: "Engineering, Humanities", rank: 221 },
  { name: "University of Duisburg-Essen", country: "Germany", field: "Engineering, Social Sciences", rank: 222 },
  { name: "University of Orleans", country: "France", field: "Environmental Science, Law", rank: 223 },
  { name: "University of Mainz", country: "Germany", field: "Chemistry, Media", rank: 224 },
  { name: "University of Tours", country: "France", field: "Renaissance Studies, Medicine", rank: 225 },
  { name: "University of Darmstadt", country: "Germany", field: "Engineering, Computer Science", rank: 226 },
  { name: "University of Angers", country: "France", field: "Plant Science, Health", rank: 227 },
  { name: "University of Bielefeld", country: "Germany", field: "Sociology, Technology", rank: 228 },
  { name: "University of Pau", country: "France", field: "Energy, Environmental Science", rank: 229 },
  { name: "University of Hannover", country: "Germany", field: "Engineering, Natural Sciences", rank: 230 },
  { name: "University of La Rochelle", country: "France", field: "Maritime Law, Environment", rank: 231 },
  { name: "University of Kassel", country: "Germany", field: "Environmental Engineering, Arts", rank: 232 },
  { name: "University of Le Mans", country: "France", field: "Acoustics, Materials Science", rank: 233 },
  { name: "University of Augsburg", country: "Germany", field: "Business, Materials Science", rank: 234 },
  { name: "University of Perpignan", country: "France", field: "Renewable Energy, Tourism", rank: 235 },
  { name: "University of Osnabrück", country: "Germany", field: "Cognitive Science, Law", rank: 236 },
  { name: "University of Avignon", country: "France", field: "Computer Science, Arts", rank: 237 },
  { name: "University of Oldenburg", country: "Germany", field: "Renewable Energy, Medicine", rank: 238 },
  { name: "University of Le Havre", country: "France", field: "Logistics, Marine Science", rank: 239 },
  { name: "University of Paderborn", country: "Germany", field: "Computer Science, Business", rank: 240 },
  { name: "University of Littoral", country: "France", field: "Environment, Tourism", rank: 241 },
  { name: "University of Bayreuth", country: "Germany", field: "African Studies, Polymer Science", rank: 242 },
  { name: "University of Valenciennes", country: "France", field: "Transport, Digital Arts", rank: 243 },
  { name: "University of Bamberg", country: "Germany", field: "Digital Humanities, Education", rank: 244 },
  { name: "University of Artois", country: "France", field: "Sports Science, Engineering", rank: 245 },
  { name: "University of Lübeck", country: "Germany", field: "Medicine, Computer Science", rank: 246 },
  { name: "University of Toulon", country: "France", field: "Marine Technology, Law", rank: 247 },
  { name: "University of Siegen", country: "Germany", field: "Media Research, Engineering", rank: 248 },
  { name: "University of Chambéry", country: "France", field: "Mountain Studies, Engineering", rank: 249 },
  { name: "University of Trier", country: "Germany", field: "Environmental Science, History", rank: 250 },

  // Rankings 251-300
  { name: "Aalborg University", country: "Denmark", field: "Engineering, Social Sciences", rank: 251 },
  { name: "University of Southern Denmark", country: "Denmark", field: "Health Sciences, Engineering", rank: 252 },
  { name: "Roskilde University", country: "Denmark", field: "Social Sciences, Natural Sciences", rank: 253 },
  { name: "IT University of Copenhagen", country: "Denmark", field: "Computer Science, Digital Design", rank: 254 },
  { name: "Copenhagen Business School", country: "Denmark", field: "Business, Economics", rank: 255 },
  { name: "University of Stavanger", country: "Norway", field: "Petroleum Engineering, Education", rank: 256 },
  { name: "Norwegian University of Life Sciences", country: "Norway", field: "Environmental Science, Veterinary", rank: 257 },
  { name: "UiT The Arctic University of Norway", country: "Norway", field: "Arctic Studies, Marine Science", rank: 258 },
  { name: "Norwegian University of Science and Technology", country: "Norway", field: "Technology, Social Sciences", rank: 259 },
  { name: "BI Norwegian Business School", country: "Norway", field: "Business, Management", rank: 260 },
  { name: "Chalmers University of Technology", country: "Sweden", field: "Technology, Engineering", rank: 261 },
  { name: "KTH Royal Institute of Technology", country: "Sweden", field: "Engineering, Architecture", rank: 262 },
  { name: "Uppsala University", country: "Sweden", field: "Medicine, Natural Sciences", rank: 263 },
  { name: "Linköping University", country: "Sweden", field: "Technology, Health Sciences", rank: 264 },
  { name: "Stockholm School of Economics", country: "Sweden", field: "Business, Economics", rank: 265 },
  { name: "University of Iceland", country: "Iceland", field: "Earth Sciences, Renewable Energy", rank: 266 },
  { name: "Reykjavik University", country: "Iceland", field: "Computer Science, Engineering", rank: 267 },
  { name: "Agricultural University of Iceland", country: "Iceland", field: "Environmental Science, Agriculture", rank: 268 },
  { name: "Bifröst University", country: "Iceland", field: "Business, Law", rank: 269 },
  { name: "Iceland University of the Arts", country: "Iceland", field: "Arts, Design", rank: 270 },
  { name: "University of Latvia", country: "Latvia", field: "Natural Sciences, Computing", rank: 271 },
  { name: "Riga Technical University", country: "Latvia", field: "Engineering, Architecture", rank: 272 },
  { name: "Latvia University of Life Sciences", country: "Latvia", field: "Agriculture, Forestry", rank: 273 },
  { name: "Vilnius University", country: "Lithuania", field: "Life Sciences, Physics", rank: 274 },
  { name: "Kaunas University of Technology", country: "Lithuania", field: "Engineering, Design", rank: 275 },
  { name: "Vytautas Magnus University", country: "Lithuania", field: "Arts, Social Sciences", rank: 276 },
  { name: "University of Tartu", country: "Estonia", field: "Medicine, Computer Science", rank: 277 },
  { name: "Tallinn University of Technology", country: "Estonia", field: "Engineering, IT", rank: 278 },
  { name: "Estonian University of Life Sciences", country: "Estonia", field: "Agriculture, Forestry", rank: 279 },
  { name: "University of Warsaw", country: "Poland", field: "Mathematics, Physics", rank: 280 },
  { name: "Jagiellonian University", country: "Poland", field: "Medicine, Humanities", rank: 281 },
  { name: "Warsaw University of Technology", country: "Poland", field: "Engineering, Architecture", rank: 282 },
  { name: "AGH University of Science and Technology", country: "Poland", field: "Mining, Engineering", rank: 283 },
  { name: "Adam Mickiewicz University", country: "Poland", field: "Social Sciences, Natural Sciences", rank: 284 },
  { name: "Charles University", country: "Czech Republic", field: "Medicine, Sciences", rank: 285 },
  { name: "Czech Technical University in Prague", country: "Czech Republic", field: "Engineering, Architecture", rank: 286 },
  { name: "Masaryk University", country: "Czech Republic", field: "Social Sciences, Medicine", rank: 287 },
  { name: "Palacký University Olomouc", country: "Czech Republic", field: "Medicine, Natural Sciences", rank: 288 },
  { name: "Brno University of Technology", country: "Czech Republic", field: "Engineering, Business", rank: 289 },
  { name: "Comenius University", country: "Slovakia", field: "Medicine, Natural Sciences", rank: 290 },
  { name: "Slovak University of Technology", country: "Slovakia", field: "Engineering, Architecture", rank: 291 },
  { name: "Technical University of Košice", country: "Slovakia", field: "Engineering, Economics", rank: 292 },
  { name: "University of Ljubljana", country: "Slovenia", field: "Engineering, Arts", rank: 293 },
  { name: "University of Maribor", country: "Slovenia", field: "Engineering, Economics", rank: 294 },
  { name: "University of Zagreb", country: "Croatia", field: "Engineering, Medicine", rank: 295 },
  { name: "University of Split", country: "Croatia", field: "Medicine, Engineering", rank: 296 },
  { name: "University of Rijeka", country: "Croatia", field: "Medicine, Maritime Studies", rank: 297 },
  { name: "University of Belgrade", country: "Serbia", field: "Engineering, Medicine", rank: 298 },
  { name: "University of Novi Sad", country: "Serbia", field: "Agriculture, Technology", rank: 299 },
  { name: "University of Niš", country: "Serbia", field: "Engineering, Medicine", rank: 300 },

  // Rankings 301-350
  { name: "Sofia University", country: "Bulgaria", field: "Physics, Mathematics", rank: 301 },
  { name: "Technical University of Sofia", country: "Bulgaria", field: "Engineering, Technology", rank: 302 },
  { name: "Medical University of Sofia", country: "Bulgaria", field: "Medicine, Pharmacy", rank: 303 },
  { name: "University of National and World Economy", country: "Bulgaria", field: "Economics, Business", rank: 304 },
  { name: "University of Chemical Technology", country: "Bulgaria", field: "Chemistry, Engineering", rank: 305 },
  { name: "University of Bucharest", country: "Romania", field: "Sciences, Humanities", rank: 306 },
  { name: "Babeș-Bolyai University", country: "Romania", field: "Sciences, Arts", rank: 307 },
  { name: "Technical University of Cluj-Napoca", country: "Romania", field: "Engineering, Architecture", rank: 308 },
  { name: "Alexandru Ioan Cuza University", country: "Romania", field: "Sciences, Arts", rank: 309 },
  { name: "Politehnica University of Bucharest", country: "Romania", field: "Engineering, Technology", rank: 310 },
  { name: "University of Athens", country: "Greece", field: "Sciences, Humanities", rank: 311 },
  { name: "Aristotle University of Thessaloniki", country: "Greece", field: "Engineering, Medicine", rank: 312 },
  { name: "National Technical University of Athens", country: "Greece", field: "Engineering, Architecture", rank: 313 },
  { name: "University of Patras", country: "Greece", field: "Engineering, Sciences", rank: 314 },
  { name: "University of Crete", country: "Greece", field: "Medicine, Sciences", rank: 315 },
  { name: "Middle East Technical University", country: "Turkey", field: "Engineering, Sciences", rank: 316 },
  { name: "Boğaziçi University", country: "Turkey", field: "Engineering, Sciences", rank: 317 },
  { name: "Istanbul Technical University", country: "Turkey", field: "Engineering, Architecture", rank: 318 },
  { name: "Hacettepe University", country: "Turkey", field: "Medicine, Sciences", rank: 319 },
  { name: "Bilkent University", country: "Turkey", field: "Engineering, Business", rank: 320 },
  { name: "Tel Aviv University", country: "Israel", field: "Medicine, Technology", rank: 321 },
  { name: "Hebrew University of Jerusalem", country: "Israel", field: "Sciences, Humanities", rank: 322 },
  { name: "Technion – Israel Institute of Technology", country: "Israel", field: "Engineering, Sciences", rank: 323 },
  { name: "Weizmann Institute of Science", country: "Israel", field: "Sciences, Technology", rank: 324 },
  { name: "Bar-Ilan University", country: "Israel", field: "Sciences, Jewish Studies", rank: 325 },
  { name: "American University of Beirut", country: "Lebanon", field: "Medicine, Engineering", rank: 326 },
  { name: "Saint Joseph University", country: "Lebanon", field: "Medicine, Law", rank: 327 },
  { name: "Lebanese American University", country: "Lebanon", field: "Business, Medicine", rank: 328 },
  { name: "University of Balamand", country: "Lebanon", field: "Medicine, Engineering", rank: 329 },
  { name: "Holy Spirit University of Kaslik", country: "Lebanon", field: "Business, Arts", rank: 330 },
  { name: "King Saud University", country: "Saudi Arabia", field: "Medicine, Engineering", rank: 331 },
  { name: "King Abdulaziz University", country: "Saudi Arabia", field: "Engineering, Medicine", rank: 332 },
  { name: "King Abdullah University of Science", country: "Saudi Arabia", field: "Science, Engineering", rank: 333 },
  { name: "King Fahd University", country: "Saudi Arabia", field: "Engineering, Sciences", rank: 334 },
  { name: "Umm Al-Qura University", country: "Saudi Arabia", field: "Islamic Studies, Engineering", rank: 335 },
  { name: "Qatar University", country: "Qatar", field: "Engineering, Business", rank: 336 },
  { name: "Carnegie Mellon University in Qatar", country: "Qatar", field: "Computer Science, Business", rank: 337 },
  { name: "Weill Cornell Medicine-Qatar", country: "Qatar", field: "Medicine", rank: 338 },
  { name: "Texas A&M University at Qatar", country: "Qatar", field: "Engineering", rank: 339 },
  { name: "Northwestern University in Qatar", country: "Qatar", field: "Media, Communication", rank: 340 },
  { name: "United Arab Emirates University", country: "UAE", field: "Engineering, Business", rank: 341 },
  { name: "American University of Sharjah", country: "UAE", field: "Engineering, Business", rank: 342 },
  { name: "University of Sharjah", country: "UAE", field: "Medicine, Engineering", rank: 343 },
  { name: "Khalifa University", country: "UAE", field: "Engineering, Sciences", rank: 344 },
  { name: "Zayed University", country: "UAE", field: "Business, Media", rank: 345 },
  { name: "Sultan Qaboos University", country: "Oman", field: "Medicine, Engineering", rank: 346 },
  { name: "University of Nizwa", country: "Oman", field: "Pharmacy, Business", rank: 347 },
  { name: "Dhofar University", country: "Oman", field: "Engineering, Business", rank: 348 },
  { name: "Sohar University", country: "Oman", field: "Engineering, Business", rank: 349 },
  { name: "German University of Technology in Oman", country: "Oman", field: "Engineering, Technology", rank: 350 },

  // Rankings 351-400
  { name: "Kuwait University", country: "Kuwait", field: "Engineering, Medicine", rank: 351 },
  { name: "American University of Kuwait", country: "Kuwait", field: "Business, Engineering", rank: 352 },
  { name: "Gulf University for Science and Technology", country: "Kuwait", field: "Business, Computer Science", rank: 353 },
  { name: "Australian College of Kuwait", country: "Kuwait", field: "Engineering, Business", rank: 354 },
  { name: "Arab Open University - Kuwait", country: "Kuwait", field: "Business, IT", rank: 355 },
  { name: "University of Bahrain", country: "Bahrain", field: "Engineering, Business", rank: 356 },
  { name: "Arabian Gulf University", country: "Bahrain", field: "Medicine, Engineering", rank: 357 },
  { name: "Ahlia University", country: "Bahrain", field: "Business, Engineering", rank: 358 },
  { name: "Applied Science University", country: "Bahrain", field: "Business, Engineering", rank: 359 },
  { name: "Royal College of Surgeons in Ireland-Bahrain", country: "Bahrain", field: "Medicine, Nursing", rank: 360 },
  { name: "Jordan University of Science and Technology", country: "Jordan", field: "Medicine, Engineering", rank: 361 },
  { name: "University of Jordan", country: "Jordan", field: "Medicine, Engineering", rank: 362 },
  { name: "Yarmouk University", country: "Jordan", field: "Sciences, Engineering", rank: 363 },
  { name: "Princess Sumaya University for Technology", country: "Jordan", field: "Engineering, IT", rank: 364 },
  { name: "German Jordanian University", country: "Jordan", field: "Engineering, Business", rank: 365 },
  { name: "Cairo University", country: "Egypt", field: "Medicine, Engineering", rank: 366 },
  { name: "Ain Shams University", country: "Egypt", field: "Medicine, Engineering", rank: 367 },
  { name: "Alexandria University", country: "Egypt", field: "Medicine, Engineering", rank: 368 },
  { name: "American University in Cairo", country: "Egypt", field: "Business, Engineering", rank: 369 },
  { name: "Mansoura University", country: "Egypt", field: "Medicine, Engineering", rank: 370 },
  { name: "University of Tehran", country: "Iran", field: "Engineering, Sciences", rank: 371 },
  { name: "Sharif University of Technology", country: "Iran", field: "Engineering, Sciences", rank: 372 },
  { name: "Amirkabir University of Technology", country: "Iran", field: "Engineering, Technology", rank: 373 },
  { name: "Iran University of Science and Technology", country: "Iran", field: "Engineering, Technology", rank: 374 },
  { name: "Shahid Beheshti University", country: "Iran", field: "Medicine, Sciences", rank: 375 },
  { name: "University of Baghdad", country: "Iraq", field: "Medicine, Engineering", rank: 376 },
  { name: "University of Mosul", country: "Iraq", field: "Medicine, Engineering", rank: 377 },
  { name: "University of Basrah", country: "Iraq", field: "Engineering, Sciences", rank: 378 },
  { name: "University of Technology, Iraq", country: "Iraq", field: "Engineering, Technology", rank: 379 },
  { name: "Al-Nahrain University", country: "Iraq", field: "Medicine, Engineering", rank: 380 },
  { name: "Damascus University", country: "Syria", field: "Medicine, Engineering", rank: 381 },
  { name: "University of Aleppo", country: "Syria", field: "Medicine, Engineering", rank: 382 },
  { name: "Tishreen University", country: "Syria", field: "Medicine, Engineering", rank: 383 },
  { name: "Al-Baath University", country: "Syria", field: "Engineering, Medicine", rank: 384 },
  { name: "Syrian Private University", country: "Syria", field: "Medicine, Pharmacy", rank: 385 },
  { name: "University of Malta", country: "Malta", field: "Medicine, Engineering", rank: 386 },
  { name: "Malta College of Arts, Science and Technology", country: "Malta", field: "Technology, Arts", rank: 387 },
  { name: "European University of Malta", country: "Malta", field: "Business, Technology", rank: 388 },
  { name: "Queen Mary University of London Malta", country: "Malta", field: "Medicine, Engineering", rank: 389 },
  { name: "American University of Malta", country: "Malta", field: "Business, Sciences", rank: 390 },
  { name: "University of Cyprus", country: "Cyprus", field: "Engineering, Sciences", rank: 391 },
  { name: "Cyprus University of Technology", country: "Cyprus", field: "Engineering, Technology", rank: 392 },
  { name: "European University Cyprus", country: "Cyprus", field: "Medicine, Business", rank: 393 },
  { name: "University of Nicosia", country: "Cyprus", field: "Medicine, Business", rank: 394 },
  { name: "Frederick University", country: "Cyprus", field: "Engineering, Business", rank: 395 },
  { name: "University of Luxembourg", country: "Luxembourg", field: "Law, Finance", rank: 396 },
  { name: "Sacred Heart University Luxembourg", country: "Luxembourg", field: "Business", rank: 397 },
  { name: "European Business University", country: "Luxembourg", field: "Business, Law", rank: 398 },
  { name: "Luxembourg School of Business", country: "Luxembourg", field: "Business", rank: 399 },
  { name: "International University of Monaco", country: "Monaco", field: "Business, Luxury Management", rank: 400 },

  // Rankings 401-450
  { name: "University of Buenos Aires", country: "Argentina", field: "Medicine, Sciences", rank: 401 },
  { name: "National University of La Plata", country: "Argentina", field: "Sciences, Engineering", rank: 402 },
  { name: "National University of Córdoba", country: "Argentina", field: "Medicine, Engineering", rank: 403 },
  { name: "National University of Rosario", country: "Argentina", field: "Agriculture, Medicine", rank: 404 },
  { name: "National University of Mar del Plata", country: "Argentina", field: "Marine Science, Engineering", rank: 405 },
  { name: "University of São Paulo", country: "Brazil", field: "Medicine, Engineering", rank: 406 },
  { name: "University of Campinas", country: "Brazil", field: "Technology, Sciences", rank: 407 },
  { name: "Federal University of Rio de Janeiro", country: "Brazil", field: "Engineering, Arts", rank: 408 },
  { name: "Federal University of Minas Gerais", country: "Brazil", field: "Engineering, Medicine", rank: 409 },
  { name: "Federal University of Rio Grande do Sul", country: "Brazil", field: "Engineering, Sciences", rank: 410 },
  { name: "Pontifical Catholic University of Chile", country: "Chile", field: "Engineering, Sciences", rank: 411 },
  { name: "University of Chile", country: "Chile", field: "Medicine, Engineering", rank: 412 },
  { name: "Federico Santa María Technical University", country: "Chile", field: "Engineering, Sciences", rank: 413 },
  { name: "University of Santiago, Chile", country: "Chile", field: "Engineering, Business", rank: 414 },
  { name: "Pontifical Catholic University of Valparaíso", country: "Chile", field: "Engineering, Sciences", rank: 415 },
  { name: "National University of Colombia", country: "Colombia", field: "Engineering, Sciences", rank: 416 },
  { name: "University of Los Andes", country: "Colombia", field: "Engineering, Medicine", rank: 417 },
  { name: "Pontifical Xavierian University", country: "Colombia", field: "Medicine, Engineering", rank: 418 },
  { name: "University of Antioquia", country: "Colombia", field: "Medicine, Engineering", rank: 419 },
  { name: "University of Valle", country: "Colombia", field: "Engineering, Sciences", rank: 420 },
  { name: "National Autonomous University of Mexico", country: "Mexico", field: "Engineering, Sciences", rank: 421 },
  { name: "Monterrey Institute of Technology", country: "Mexico", field: "Engineering, Business", rank: 422 },
  { name: "National Polytechnic Institute", country: "Mexico", field: "Engineering, Sciences", rank: 423 },
  { name: "University of Guadalajara", country: "Mexico", field: "Medicine, Engineering", rank: 424 },
  { name: "Autonomous Metropolitan University", country: "Mexico", field: "Sciences, Engineering", rank: 425 },
  { name: "Pontifical Catholic University of Peru", country: "Peru", field: "Engineering, Arts", rank: 426 },
  { name: "National University of San Marcos", country: "Peru", field: "Medicine, Sciences", rank: 427 },
  { name: "University of Lima", country: "Peru", field: "Business, Engineering", rank: 428 },
  { name: "National University of Engineering", country: "Peru", field: "Engineering, Sciences", rank: 429 },
  { name: "Cayetano Heredia University", country: "Peru", field: "Medicine, Sciences", rank: 430 },
  { name: "Central University of Venezuela", country: "Venezuela", field: "Medicine, Engineering", rank: 431 },
  { name: "Simón Bolívar University", country: "Venezuela", field: "Engineering, Sciences", rank: 432 },
  { name: "Andrés Bello Catholic University", country: "Venezuela", field: "Law, Engineering", rank: 433 },
  { name: "University of Zulia", country: "Venezuela", field: "Engineering, Medicine", rank: 434 },
  { name: "University of the Andes", country: "Venezuela", field: "Sciences, Engineering", rank: 435 },
  { name: "University of Costa Rica", country: "Costa Rica", field: "Medicine, Engineering", rank: 436 },
  { name: "Costa Rica Institute of Technology", country: "Costa Rica", field: "Engineering, Business", rank: 437 },
  { name: "National University of Costa Rica", country: "Costa Rica", field: "Environmental Science, Arts", rank: 438 },
  { name: "Latin University of Costa Rica", country: "Costa Rica", field: "Business, Engineering", rank: 439 },
  { name: "Universidad Latina", country: "Costa Rica", field: "Medicine, Engineering", rank: 440 },
  { name: "University of Panama", country: "Panama", field: "Medicine, Engineering", rank: 441 },
  { name: "Technological University of Panama", country: "Panama", field: "Engineering, Technology", rank: 442 },
  { name: "Catholic University Santa María la Antigua", country: "Panama", field: "Business, Law", rank: 443 },
  { name: "Latin University of Panama", country: "Panama", field: "Business, Engineering", rank: 444 },
  { name: "Quality Leadership University", country: "Panama", field: "Business, Technology", rank: 445 },
  { name: "University of Puerto Rico", country: "Puerto Rico", field: "Sciences, Engineering", rank: 446 },
  { name: "Inter American University of Puerto Rico", country: "Puerto Rico", field: "Business, Engineering", rank: 447 },
  { name: "Pontifical Catholic University of Puerto Rico", country: "Puerto Rico", field: "Education, Business", rank: 448 },
  { name: "Universidad del Sagrado Corazón", country: "Puerto Rico", field: "Communications, Business", rank: 449 },
  { name: "Universidad Central del Caribe", country: "Puerto Rico", field: "Medicine, Sciences", rank: 450 },

  // Rankings 451-500
  { name: "University of the West Indies", country: "Jamaica", field: "Medicine, Engineering", rank: 451 },
  { name: "University of Technology, Jamaica", country: "Jamaica", field: "Technology, Engineering", rank: 452 },
  { name: "Northern Caribbean University", country: "Jamaica", field: "Business, Technology", rank: 453 },
  { name: "University of the Commonwealth Caribbean", country: "Jamaica", field: "Business, Technology", rank: 454 },
  { name: "Caribbean Maritime University", country: "Jamaica", field: "Maritime Studies, Engineering", rank: 455 },
  { name: "University of Havana", country: "Cuba", field: "Sciences, Medicine", rank: 456 },
  { name: "Universidad Tecnológica de La Habana", country: "Cuba", field: "Engineering, Technology", rank: 457 },
  { name: "Universidad de Oriente", country: "Cuba", field: "Medicine, Engineering", rank: 458 },
  { name: "Universidad Central de Las Villas", country: "Cuba", field: "Engineering, Sciences", rank: 459 },
  { name: "Instituto Superior Politécnico José Antonio Echeverría", country: "Cuba", field: "Engineering, Architecture", rank: 460 },
  { name: "University of the Dominican Republic", country: "Dominican Republic", field: "Medicine, Engineering", rank: 461 },
  { name: "Pontificia Universidad Católica Madre y Maestra", country: "Dominican Republic", field: "Engineering, Business", rank: 462 },
  { name: "Universidad Iberoamericana", country: "Dominican Republic", field: "Medicine, Business", rank: 463 },
  { name: "Instituto Tecnológico de Santo Domingo", country: "Dominican Republic", field: "Engineering, Business", rank: 464 },
  { name: "Universidad APEC", country: "Dominican Republic", field: "Business, Technology", rank: 465 },
  { name: "University of Trinidad and Tobago", country: "Trinidad and Tobago", field: "Engineering, Arts", rank: 466 },
  { name: "University of the Southern Caribbean", country: "Trinidad and Tobago", field: "Business, Education", rank: 467 },
  { name: "College of Science, Technology and Applied Arts", country: "Trinidad and Tobago", field: "Technology, Arts", rank: 468 },
  { name: "University of the West Indies St. Augustine", country: "Trinidad and Tobago", field: "Engineering, Medicine", rank: 469 },
  { name: "School of Business and Computer Science", country: "Trinidad and Tobago", field: "Business, Technology", rank: 470 },
  { name: "Anton de Kom University", country: "Suriname", field: "Medicine, Technology", rank: 471 },
  { name: "Polytechnic College University", country: "Suriname", field: "Engineering, Technology", rank: 472 },
  { name: "Institute for Graduate Studies and Research", country: "Suriname", field: "Research, Technology", rank: 473 },
  { name: "University of Guyana", country: "Guyana", field: "Agriculture, Engineering", rank: 474 },
  { name: "Texila American University", country: "Guyana", field: "Medicine, Business", rank: 475 },
  { name: "University of Belize", country: "Belize", field: "Agriculture, Medicine", rank: 476 },
  { name: "Galen University", country: "Belize", field: "Business, Education", rank: 477 },
  { name: "American University of the Caribbean", country: "Sint Maarten", field: "Medicine", rank: 478 },
  { name: "University of Sint Maarten", country: "Sint Maarten", field: "Business, Technology", rank: 479 },
  { name: "St. James School of Medicine", country: "Sint Maarten", field: "Medicine", rank: 480 },
  { name: "University of Curaçao", country: "Curaçao", field: "Law, Engineering", rank: 481 },
  { name: "Caribbean International University", country: "Curaçao", field: "Business, Technology", rank: 482 },
  { name: "Inter-Continental University of the Caribbean", country: "Curaçao", field: "Business, Technology", rank: 483 },
  { name: "University of Aruba", country: "Aruba", field: "Law, Business", rank: 484 },
  { name: "Xavier University School of Medicine", country: "Aruba", field: "Medicine", rank: 485 },
  { name: "University of the Bahamas", country: "Bahamas", field: "Business, Education", rank: 486 },
  { name: "Ross University School of Medicine", country: "Barbados", field: "Medicine", rank: 487 },
  { name: "University of the West Indies Cave Hill", country: "Barbados", field: "Law, Medicine", rank: 488 },
  { name: "American University of Barbados", country: "Barbados", field: "Medicine", rank: 489 },
  { name: "Barbados Community College", country: "Barbados", field: "Technology, Arts", rank: 490 },
  { name: "St. George's University", country: "Grenada", field: "Medicine, Veterinary", rank: 491 },
  { name: "T.A. Marryshow Community College", country: "Grenada", field: "Business, Technology", rank: 492 },
  { name: "University of Science, Arts and Technology", country: "Montserrat", field: "Medicine, Arts", rank: 493 },
  { name: "American University of Antigua", country: "Antigua and Barbuda", field: "Medicine", rank: 494 },
  { name: "University of Health Sciences Antigua", country: "Antigua and Barbuda", field: "Medicine", rank: 495 },
  { name: "Windsor University School of Medicine", country: "Saint Kitts and Nevis", field: "Medicine", rank: 496 },
  { name: "University of Medicine and Health Sciences", country: "Saint Kitts and Nevis", field: "Medicine", rank: 497 },
  { name: "International University of the Health Sciences", country: "Saint Kitts and Nevis", field: "Medicine", rank: 498 },
  { name: "Saint James School of Medicine", country: "Saint Vincent", field: "Medicine", rank: 499 },
  { name: "Trinity School of Medicine", country: "Saint Vincent", field: "Medicine", rank: 500 }
];

export default function TopUniversitiesPage() {
  return (
    <main className="max-w-5xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold mb-4 text-center">
        🌍 Top Universities for International Students
      </h1>
      <p className="text-lg text-gray-600 text-center mb-10">
        Discover the best universities around the world trusted by global students. Skyland Immigration helps you apply to top-ranked institutions across the USA, UK, Canada, and more.
      </p>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {universities.map((uni, index) => (
          <div
            key={index}
            className="bg-white rounded-2xl shadow p-6 border border-gray-100 hover:shadow-md transition"
          >
            <h2 className="text-xl font-semibold mb-1">{uni.name}</h2>
            <p className="text-sm text-gray-700">📍 {uni.country}</p>
            <p className="text-sm text-gray-600">🔬 Fields: {uni.field}</p>
            <span className="inline-block mt-2 bg-blue-100 text-blue-800 text-xs font-medium px-2 py-1 rounded">
              🌟 Rank #{uni.rank}
            </span>
          </div>
        ))}
      </div>

      <div className="mt-16 text-center">
        <h3 className="text-2xl font-semibold mb-4">Need help applying?</h3>
        <p className="text-md text-gray-700 mb-4">
          Our expert visa consultants are here to guide you through the application and admission process.
        </p>
        <a
          href="/contact"
          className="inline-block bg-blue-600 text-white px-6 py-3 rounded-xl hover:bg-blue-700 transition"
        >
          Contact Us Today
        </a>
      </div>
    </main>
  );
}
