import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from './components/Header';
import { Topbar } from "./components/Topbar";
import Banner from "./components/Banner";
import Footer  from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Topbar phone="9032420020" email="info@skylandimmigration.com" hours="Mon - Fri: 9:00 AM - 6:00 PM" />
        <Banner
          title="Flash Sale! 30% off all services today only."
          cta={{ text: 'Claim Offer', url: '/offer' }}
        />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
